export const keywords = [
  "virtue",
  "wisdom",
  "knowledge",
  "justice",
  "courage",
  "truth",
  "self reflection",
  "dialogue",
  "ethics",
  "moral",
  "integrity",
  "philosophy",
  "logic",
  "reason",
  "humility",
  "ignorance",
  "self knowledge",
  "questions",
  "soul",
  "goodness",
  "honor",
  "excellence",
  "temperance",
  "self control",
  "purpose",
  "learning",
  "discipline",
  "accountability",
  "belief",
  "piety",
  "justice",
  "dialectic",
  "reflection",
  "introspection",
  "argument",
  "cross examination",
  "ethics",
  "human nature",
  "pursuit of truth",
  "civic duty",
  "self improvement",
  "critical thinking",
  "virtue ethics"
];
